export const monitoringSystems = [
  {
    code: "GBM",
    title: "Ganges–Brahmaputra–Meghna Drought and Flood Monitoring System",
    titleZh: "恒河–布拉马普特河–梅格纳河流域干旱洪水监测系统",
    text: "An operational view of drought, flood depth, flood risk and discharge across the GBM transboundary basin.",
    href: "http://121.199.2.154/GBMMS.html",
  },
  {
    code: "LMRB",
    title: "Lancang–Mekong Drought and Flood Monitoring System",
    titleZh: "澜沧江–湄公河流域干旱洪水监测系统",
    text: "Basin-scale monitoring of drought conditions, flood dynamics, inundation depth, risk and river discharge.",
    href: "http://121.199.2.154/LMRBMS.html",
  },
];

export const openData = [
  {
    year: "1951–2024",
    title: "A 0.1° Resolution Bias-Corrected Daily Meteorological Dataset for the Source Region of the Yellow River",
    titleZh: "黄河源逐日0.1°校正气象数据集（1951–2024）",
    text: "Daily 0.1° bias-corrected precipitation, temperature and wind-speed data for the Source Region of the Yellow River, covering 1951–2024.",
    repository: "National Tibetan Plateau Data Center",
    doi: "10.11888/Atmos.tpdc.303450",
    href: "https://data.tpdc.ac.cn/zh-hans/data/188649f5-bbef-4588-a44c-e6af578b0238",
  },
];

export const publications = [
  {
    year: "2026",
    title: "Multiscale Spatiotemporal Variations of Ecosystem Water Limitation and Its Divergent Drivers on the Tibetan Plateau",
    authors: "Wang J, Chang Y, Shangguan D, Dong Y, Zhao Q, He X, Zhang S",
    journal: "Ecohydrology · 19(5), e70244",
    href: "https://doi.org/10.1002/eco.70244",
  },
  {
    year: "2026",
    title: "Multidimensional evaluation of the gridded precipitation datasets over the source region of the Yellow River",
    authors: "Wang J, Zhang Q, Bao H, Yun X, Tang Q",
    journal: "Journal of Hydrometeorology · 27(6), 801–821",
    href: "https://doi.org/10.1175/JHM-D-26-0019.1",
  },
  {
    year: "2025",
    title: "Evolution and Attribution of Flood Volume in the Source Region of the Yellow River",
    authors: "Wang J, Shangguan D, Ding Y, Chang Y",
    journal: "Remote Sensing · 17(8), 1342",
    href: "https://doi.org/10.3390/rs17081342",
  },
  {
    year: "2024",
    title: "How do gridded meteorological datasets perform in a typical data-scarce cryospheric basin?",
    authors: "Chang Y, Shangguan D, Ding Y, Zhang S, Zhao Q, Wang J",
    journal: "Advances in Climate Change Research · 15(6), 1027–1039",
    href: "https://doi.org/10.1016/j.accre.2024.10.004",
  },
  {
    year: "2024",
    title: "Impacts of large-scale climatic circulation on floods through precipitation and temperature in the Lancang-Mekong River Basin",
    authors: "Wang J, Yun X, Chen A, Gaffney P, Haile G, Tang Q",
    journal: "Science of the Total Environment · 908, 168082",
    href: "https://doi.org/10.1016/j.scitotenv.2023.168082",
  },
  {
    year: "2022",
    title: "Flood inundation in the Lancang-Mekong River Basin: Assessing the role of summer monsoon",
    authors: "Wang J, Tang Q, Yun X, Chen A, Sun S, Yamazaki D",
    journal: "Journal of Hydrology · 612, 128075",
    href: "https://doi.org/10.1016/j.jhydrol.2022.128075",
  },
  {
    year: "2022",
    title: "Impacts of summer monsoons on flood characteristics in the Lancang-Mekong River Basin",
    authors: "Wang J, Tang Q, Chen A, Tang Y, Xu X, Yun X, Mu M, Wright N G, Chen D",
    journal: "Journal of Hydrology · 604, 127256",
    href: "https://doi.org/10.1016/j.jhydrol.2021.127256",
  },
  {
    year: "2021",
    title: "Modeling daily floods in the Lancang-Mekong River Basin using an improved hydrological-hydrodynamic model",
    authors: "Wang J, Yun X, Pokhrel P, Yamazaki D, Chen A, Zhao Q, Tang Q",
    journal: "Water Resources Research · 57(8), e2021WR029734",
    href: "https://doi.org/10.1029/2021WR029734",
  },
  {
    year: "2021",
    title: "The effect of hillslope geometry on Hortonian rainfall-infiltration-runoff processes",
    authors: "Wang J, Chen L",
    journal: "Journal of Hydrology · 594, 125962",
    href: "https://doi.org/10.1016/j.jhydrol.2021.125962",
  },
  {
    year: "2018",
    title: "Modeling rainfall infiltration on hillslopes using Flux-concentration relation and time compression approximation",
    authors: "Wang J, Chen L, Yu Z",
    journal: "Journal of Hydrology · 557, 243–253",
    href: "https://doi.org/10.1016/j.jhydrol.2017.12.031",
  },
  {
    year: "2017",
    title: "Influence of slope gradient on hillslope rainfall-runoff processes",
    authors: "Wang J, Wang Y, Xu X, Chen L",
    authorsZh: "王杰，王妍，许晓梁，陈力",
    titleZh: "坡度对坡面降雨产流规律的影响",
    journal: "Journal of Hohai University (Natural Sciences) · 45(4), 373–377",
    journalZh: "河海大学学报（自然科学版）",
  },
  {
    year: "2016",
    title: "Analysis of abrupt changes in annual precipitation in western China using a median change-point test",
    authors: "Wang J, Pei B",
    authorsZh: "王杰，裴斌",
    titleZh: "基于中位数突变检验方法的西部地区年降雨突变分析",
    journal: "Water Resources and Power · 2016(12), 25–27",
    journalZh: "水电能源科学",
  },
  {
    year: "2014",
    title: "Application of the Gauss-Newton method to Pearson Type III curve fitting",
    authors: "Wang J, Wan C, Zheng M, Han C",
    authorsZh: "王杰，万程炜，郑敏杰，韩翀",
    titleZh: "高斯牛顿法在皮尔逊Ⅲ型曲线适线中的应用",
    journal: "Yellow River · 2014(09), 27–30",
    journalZh: "人民黄河",
  },
  {
    year: "2026",
    title: "Extreme precipitation dominates the increase in total precipitation over the source region of the Yellow River",
    authors: "Chen S, Mu M, Tian L, Song J, Feng Y, Wang J, Zhang B, Pan B",
    journal: "Weather and Climate Extremes · 100925",
  },
  {
    year: "2025",
    title: "Refining snow-streamflow dynamics in a Tibetan Plateau basin by incorporating snow depth and topography",
    authors: "Tian L, Wang W, Ma X, Zhang H, Guo S, Yang K, Wang J, Wang L",
    journal: "Journal of Hydrology · 657, 133057",
  },
  {
    year: "2025",
    title: "Optimizing Lancang-Mekong hydropower portfolio effectively reduces greenhouse gas emissions",
    authors: "Yun X, Tang Q, Wang J, Sun S, Bao H, Pokhrel Y, Luo L, Chen D",
    journal: "Environmental Impact Assessment Review · 114, 107952",
  },
  {
    year: "2025",
    title: "Impact of tropical cyclone precipitation on fluvial discharge in the Lancang-Mekong River Basin",
    authors: "Chen A, Wang J, Toumi R, Huang H, Yang L, Chen D, He B, Liu J",
    journal: "Geophysical Research Letters · 52(8), e2024GL113199",
  },
  {
    year: "2024",
    title: "Impact of tropical cyclones and socioeconomic exposure on flood risk distribution in the Mekong Basin",
    authors: "Chen A, Pokhrel Y, Chen D, Huang H, Dai Z, He B, Wang J, Li J, Wang H, Liu J",
    journal: "Communications Earth & Environment · 5(1), 704",
  },
  {
    year: "2024",
    title: "Modelling to assess the suitability of a hydrological-hydrodynamic model under hydropower development impacts in the Lancang-Mekong River Basin",
    authors: "Yun X, Song J, Wang J, Bao H",
    journal: "Journal of Hydrology · 637, 131393",
  },
  {
    year: "2023",
    title: "An analysis of the spatial variation of tropical cyclone rainfall trends in Mainland Southeast Asia",
    authors: "Chen A, Huang H, Wang J, Li Y, Chen D, Liu J",
    journal: "International Journal of Climatology · 43(13), 5912–5926",
  },
  {
    year: "2023",
    title: "Reservoir operation affects propagation from meteorological to hydrological extremes in the Lancang-Mekong River Basin",
    authors: "Yun X, Tang Q, Wang J, Li J, Li Y, Bao H",
    journal: "Science of the Total Environment · 896, 165297",
  },
  {
    year: "2023",
    title: "Projected seasonal changes in future rainfall erosivity over the Lancang-Mekong River Basin under the CMIP6 scenarios",
    authors: "Xu X, Yun X, Tang Q, Cui H, Wang J, Zhang L, Chen D",
    journal: "Journal of Hydrology · 620, 129444",
  },
  {
    year: "2021",
    title: "Reducing climate-change-induced flood at the cost of hydropower in the Lancang-Mekong River Basin",
    authors: "Yun X, Tang Q, Sun S, Wang J",
    journal: "Geophysical Research Letters · 48(20), e2021GL094243",
  },
  {
    year: "2021",
    title: "Multidecadal variability of the Tonle Sap Lake flood pulse regime",
    authors: "Chen A, Liu J, Kummu M, Varis O, Tang Q, Mao G, Wang J, Chen D",
    journal: "Hydrological Processes · 35(9), e14327",
  },
  {
    year: "2020",
    title: "Impacts of climate change and reservoir operation on streamflow and flood characteristics in the Lancang-Mekong River Basin",
    authors: "Yun X, Tang Q, Wang J, Liu X, Zhang Y, Lu H, Wang Y, Zhang L, Chen D",
    journal: "Journal of Hydrology · 590, 125472",
  },
  {
    year: "2020",
    title: "Long-term spatiotemporal variation of drought patterns over the Greater Horn of Africa",
    authors: "Haile G G, Tang Q, Leng G, Jia G, Wang J, Cai D, Sun S, Baniya B, Zhang Q",
    journal: "Science of the Total Environment · 704, 135299",
  },
  {
    year: "2020",
    title: "Impacts of climate change on upstream-downstream water-resource cooperation potential in the Lancang-Mekong River Basin",
    authors: "Yun X, Tang Q, Xu X, Zhou Y, Liu X, Wang J, Sun S",
    authorsZh: "运晓博，汤秋鸿，徐锡蒙，周园园，刘星才，王杰，孙思奥",
    titleZh: "气候变化对澜湄流域上下游水资源合作潜力的影响",
    journal: "Advances in Climate Change Research · 16(5), 555–563",
    journalZh: "气候变化研究进展",
  },
  {
    year: "2019",
    title: "Cascading effects of changes in the Asian Water Tower on downstream water resources",
    authors: "Tang Q, Liu X, Zhou Y, Wang J, Yun X",
    authorsZh: "汤秋鸿，刘星才，周园园，王杰，运晓博",
    titleZh: "“亚洲水塔”变化对下游水资源的连锁效应",
    journal: "Bulletin of the Chinese Academy of Sciences · 34(11), 1306–1312",
    journalZh: "中国科学院院刊",
  },
  {
    year: "2017",
    title: "Methodological comparison of alpine meadow evapotranspiration on the Tibetan Plateau, China",
    authors: "Chang Y, Wang J, Qin D, Ding Y, Zhao Q, Liu F, Zhang S",
    journal: "PLOS ONE · 12(12), e0189059",
  },
];

export const books = [
  {
    year: "2024",
    title: "Water Hazards: Drought and Flood",
    authors: "Tang Q, Yun X, Wang J, Deng H, Liu B, Tran T C, …, Gaffney P P",
    text: "In Water Resources in the Lancang-Mekong River Basin: Impact of Climate Change and Human Interventions, pp. 255–281. Springer Nature Singapore.",
  },
  {
    year: "2022",
    title: "Flooding Risk in the Lancang-Mekong River Basin under Global Change",
    authors: "Yun X, Wang J, Wu H, et al.",
    text: "In Climate Risk and Sustainable Water Management (Tang Q, Leng G, eds.), pp. 29–46. Cambridge University Press.",
  },
];

export const intellectualProperty = [
  {
    year: "2025",
    title: "Basin High-Performance Water-Element Monitoring and Forecasting System Software V1.0",
    titleZh: "流域高性能水要素监测与预报系统软件V1.0",
    authors: "Jie Wang · Qian Zhang / 王杰 · 张倩",
    registration: "2025SR0415905",
  },
  {
    year: "2025",
    title: "Joint Hydrological-Hydrodynamic Model Parameter Optimization System Software V1.0",
    titleZh: "联合水文水动力模型参数优化系统软件V1.0",
    authors: "Jie Wang · Qian Zhang / 王杰 · 张倩",
    registration: "2025SR0410597",
  },
  {
    year: "2024",
    title: "Large-Scale Basin Flood-Risk Threshold Generation Software V1.0",
    titleZh: "流域大尺度洪水风险阈值生成软件V1.0",
    authors: "Jie Wang · Qian Zhang / 王杰 · 张倩",
    registration: "2024SR1190472",
  },
  {
    year: "2024",
    title: "Climate Model Bias Correction and Post-Processing Software V1.0",
    titleZh: "气候模式偏差纠正和后处理软件V1.0",
    authors: "Jie Wang · Qian Zhang / 王杰 · 张倩",
    registration: "2024SR1130279",
  },
  {
    year: "2020",
    title: "High-Resolution Hourly Flood Monitoring System V1.0",
    titleZh: "高分辨率逐时洪水监测系统V1.0",
    authors: "Jie Wang · Qiuhong Tang · Ximeng Xu / 王杰 · 汤秋鸿 · 徐锡蒙",
    registration: "2020SR1072110",
  },
  {
    year: "2020",
    title: "High-Resolution Daily Flood Monitoring and Forecasting System V1.0",
    titleZh: "高分辨率逐日洪水监测预报系统V1.0",
    authors: "Jie Wang · Qiuhong Tang · Ximeng Xu / 王杰 · 汤秋鸿 · 徐锡蒙",
    registration: "2020SR1072922",
  },
  {
    year: "2016",
    title: "Hydrological Frequency Curve-Fitting Software V1.0",
    titleZh: "水文频率适线软件V1.0",
    authors: "Jie Wang · Li Chen · Xiaobing Chen / 王杰 · 陈力 · 陈孝兵",
    registration: "2016SR117646",
  },
];

export const hostedProjects = [
  {
    period: "2024–2026",
    title: "Flood Genesis and Future Change Projection in the Source Region of the Yellow River",
    titleZh: "黄河源洪水成因解析和未来变化预估",
    sponsor: "National Natural Science Foundation of China · Young Scientists Fund (Category C)",
    sponsorZh: "国家自然科学基金青年科学基金项目（C类）",
    meta: "Principal Investigator ·  Active",
    metaZh: "主持（执行）",
  },
  {
    period: "2023–2025",
    title: "Flood Simulation and Projection in the Ganges-Brahmaputra-Meghna Basin",
    titleZh: "恒河-布拉马普特河-梅格纳河洪水模拟与预估",
    sponsor: "China Association for Science and Technology · 9th Young Elite Scientists Sponsorship Program",
    sponsorZh: "中国科协第九届青年人才托举工程项目",
    meta: "Principal Investigator  · Completed",
    metaZh: "主持（结题）",
  },
  {
    period: "2025–2026",
    title: "Testing and Optimization of Meteorological Risk Warning Products for Reservoir Rainstorm and Flood Disasters in Xinjiang",
    titleZh: "新疆水库暴雨洪水灾害气象风险预警产品测试与优化",
    sponsor: "National Meteorological Centre · Commissioned Project",
    sponsorZh: "中国气象局国家气象中心业务委托项目",
    meta: "Principal Investigator  · Completed",
    metaZh: "主持（结题）",
  },
  {
    period: "2023–2024",
    title: "Development, Improvement and Calibration of a Refined Distributed Forecasting Model for the Liujiang River Basin",
    titleZh: "柳江流域精细化分布式预报模型建设改进与调试",
    sponsor: "National Meteorological Centre · Commissioned Project",
    sponsorZh: "中国气象局国家气象中心业务委托项目",
    meta: "Principal Investigator · Completed",
    metaZh: "主持（结题）",
  },
  {
    period: "2025",
    title: "Hydrometeorological Model Upgrade, Testing, Validation and Code Optimization",
    titleZh: "水文气象模型升级测试检验与代码优化",
    sponsor: "National Meteorological Centre · Commissioned Project",
    sponsorZh: "中国气象局国家气象中心业务委托项目",
    meta: "Principal Investigator · Completed",
    metaZh: "主持（结题）",
  },
  {
    period: "2022–2023",
    title: "Hydrological-Hydrodynamic Simulation Data Processing for Transboundary Basins in Southeast and South Asia",
    titleZh: "东南亚-南亚跨境流域水文水动力模拟数据加工",
    sponsor: "Institute of Geographic Sciences and Natural Resources Research, Chinese Academy of Sciences · Commissioned Project",
    sponsorZh: "中科院地理科学与资源研究所业务委托项目",
    meta: "Principal Investigator ·  Completed",
    metaZh: "主持（结题）",
  },
  {
    period: "2022–2024",
    title: "Future Flood Projection and Impact Assessment in the Lancang-Mekong River Basin",
    titleZh: "澜湄流域未来洪水预测与影响评估",
    sponsor: "Fundamental Research Funds for the Central Universities",
    sponsorZh: "中央高校基本科研业务费",
    meta: "Principal Investigator · Completed",
    metaZh: "主持（结题）",
  },
];
